# Generated by Django 4.2.16 on 2026-05-04 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                ("date", models.DateTimeField(verbose_name="Fecha y hora")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/posters/",
                        verbose_name="Poster",
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de tickets"
                    ),
                ),
                (
                    "price_info",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Información de precio"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("cancelled", "Cancelado"),
                            ("sold_out", "Agotado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si el evento debe aparecer destacado",
                        verbose_name="Destacado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("address", models.CharField(max_length=300, verbose_name="Dirección")),
                (
                    "city",
                    models.CharField(
                        default="Montevideo", max_length=100, verbose_name="Ciudad"
                    ),
                ),
                (
                    "maps_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Google Maps"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="events/photos/", verbose_name="Imagen"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Caption"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de aparicion en la galeria",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de evento",
                "verbose_name_plural": "Fotos de eventos",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.venue",
                verbose_name="Venue",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventphoto",
            constraint=models.UniqueConstraint(
                fields=("event", "order"), name="unique_event_photo_order"
            ),
        ),
    ]
