# Generated by Django 4.2.30 on 2026-06-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_since',
            field=models.PositiveIntegerField(blank=True, help_text='Año de inicio del evento', null=True, verbose_name='Activo desde (año)'),
        ),
        migrations.AddField(
            model_name='event',
            name='average_attendance',
            field=models.PositiveIntegerField(blank=True, help_text='Promedio de personas por apertura', null=True, verbose_name='Promedio de asistencia'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('matinee', 'Matineé (12-15 años)'), ('plus15', '+15 (15-17 años)'), ('plus18', '+18 (18+ años)'), ('coproduccion_internacional', 'Co-Producción Internacional'), ('coproduccion_nacional', 'Co-Producción Nacional')], help_text='Categoría del evento para organización', max_length=50, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(blank=True, help_text='Ej: Mensual, Trimestral, Anual', max_length=100, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo para mostrar en la página de categorías', null=True, upload_to='events/logos/', verbose_name='Logo del evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, help_text='Descripción detallada para la página de categorías', verbose_name='Descripción larga'),
        ),
    ]
