# Generated by Django 4.2.16 on 2026-04-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="events/photos/", verbose_name="Imagen"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Caption"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de aparicion en la galeria",
                        verbose_name="Orden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de evento",
                "verbose_name_plural": "Fotos de eventos",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
