# Generated by Django 4.2.16 on 2026-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_active_since_event_average_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recap_video',
            field=models.FileField(blank=True, help_text='Video resumen del evento para la galeria de momentos', null=True, upload_to='events/videos/', verbose_name='Video recap'),
        ),
    ]
