# Generated by Django 4.2.16 on 2026-07-28 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('hero_title', models.CharField(default='¿Quiénes somos?', help_text="Título grande de la sección 'Quiénes somos' (Home y /nosotros)", max_length=200, verbose_name='Título principal')),
            ],
            options={
                'verbose_name': 'Página Nosotros',
                'verbose_name_plural': 'Página Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.CharField(help_text='Ej: 200+, 150+, 200.000+', max_length=20, verbose_name='Valor')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('is_number', models.BooleanField(default=True, help_text='Si está marcado, el valor se anima contando hasta el número al entrar en pantalla', verbose_name='Es numérico')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = primero)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryBlock',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, help_text='Dejar vacío para no mostrar título en este bloque', max_length=200, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image', models.ImageField(blank=True, upload_to='about/story/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = primero)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Bloque de historia',
                'verbose_name_plural': 'Bloques de historia',
                'ordering': ['order'],
            },
        ),
    ]
