# Generated by Django 4.2.16 on 2026-05-04 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=300, verbose_name="Asunto")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("read", models.BooleanField(default=False, verbose_name="Leído")),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "ordering": ["-created_at"],
            },
        ),
    ]
