# Generated by Django 4.2.16 on 2026-04-29 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
