# Generated by Django 4.2.16 on 2026-03-27 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text='Resumen corto para listados', max_length=500, verbose_name='Extracto')),
                ('body', models.TextField(verbose_name='Contenido')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Imagen de portada')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_at'],
            },
        ),
    ]
