import type { Event, GalleryItem, Post, Sponsor } from './types'

// Mock data for events
export const mockEvents: Event[] = [
  {
    slug: 'hormiga-negra-x',
    name: 'HORMIGA NEGRA X',
    venue: 'Cine Universitario',
    date: '2026-04-12',
    day: '12',
    month: 'ABR',
    weekday: 'SÁB',
    price: '$U 350 anticipadas',
    status: 'en-venta',
    featured: true,
    description: 'La décima edición de nuestra experiencia más icónica. Una noche de arte, música electrónica y conexiones genuinas en el emblemático Cine Universitario.',
    image: '/mock-photos/event-1.jpeg',
  },
  {
    slug: 'subterranea-vol4',
    name: 'SUBTERRANEA VOL.4',
    venue: 'La Trastienda',
    date: '2026-04-19',
    day: '19',
    month: 'ABR',
    weekday: 'VIE',
    price: '$U 300 anticipadas',
    status: 'en-venta',
    description: 'Cuarta edición de nuestra serie underground. Experiencia audiovisual única en La Trastienda con los mejores DJs de la escena local.',
    image: '/mock-photos/event-2.jpeg',
  },
  {
    slug: 'techno-night-mvd',
    name: 'TECHNO NIGHT MVD',
    venue: 'Sala Zitarrosa',
    date: '2026-04-26',
    day: '26',
    month: 'ABR',
    weekday: 'VIE',
    price: '$U 280 anticipadas',
    status: 'en-venta',
    featured: true,
    description: 'Una noche dedicada al techno más puro. DJs internacionales y locales en la mejor sala de Montevideo.',
    image: '/mock-photos/event-3.jpeg',
  },
  {
    slug: 'open-air-otono',
    name: 'OPEN AIR OTOÑO',
    venue: 'Parque Rodó',
    date: '2026-05-03',
    day: '03',
    month: 'MAY',
    weekday: 'SÁB',
    price: '',
    status: 'agotado',
    description: 'Festival al aire libre en el corazón del Parque Rodó. SOLD OUT. Una experiencia única que celebra la música y la cultura uruguaya.',
    image: '/mock-photos/event-4.jpeg',
  },
  {
    slug: 'warehouse-party',
    name: 'WAREHOUSE PARTY',
    venue: 'Espacio Industrial',
    date: '2026-05-10',
    day: '10',
    month: 'MAY',
    weekday: 'VIE',
    price: '$U 320 anticipadas',
    status: 'en-venta',
    description: 'Rave en un espacio industrial transformado. House y techno hasta el amanecer en un ambiente único.',
    image: '/mock-photos/event-5.jpg',
  },
  {
    slug: 'hormiga-sessions-01',
    name: 'HORMIGA SESSIONS 01',
    venue: 'Club Azul',
    date: '2026-05-17',
    day: '17',
    month: 'MAY',
    weekday: 'SÁB',
    price: '$U 400 anticipadas',
    status: 'en-venta',
    featured: true,
    description: 'Primera edición de nuestra nueva serie de experiencias íntimas. Arte, música experimental y conexiones genuinas en un espacio único.',
    image: '/mock-photos/event-1.jpeg',
  },
  {
    slug: 'sunset-electronico',
    name: 'SUNSET ELECTRÓNICO',
    venue: 'Playa Ramírez',
    date: '2026-05-24',
    day: '24',
    month: 'MAY',
    weekday: 'SÁB',
    price: '$U 250 anticipadas',
    status: 'en-venta',
    description: 'Festival al atardecer en la rambla. Deep house y chill vibes mientras el sol se pone sobre el Río de la Plata.',
    image: '/mock-photos/event-2.jpeg',
  },
  {
    slug: 'underground-collective',
    name: 'UNDERGROUND COLLECTIVE',
    venue: 'La Trastienda',
    date: '2026-05-31',
    day: '31',
    month: 'MAY',
    weekday: 'VIE',
    price: '$U 350 anticipadas',
    status: 'en-venta',
    description: 'Colectivo de DJs locales presenta una noche de música electrónica experimental y avant-garde.',
    image: '/mock-photos/event-3.jpeg',
  },
  {
    slug: 'aniversario-30-anos',
    name: 'ANIVERSARIO 30 AÑOS',
    venue: 'TBA',
    date: '2026-06-07',
    day: '07',
    month: 'JUN',
    weekday: 'SÁB',
    price: '',
    status: 'proximamente',
    description: 'Celebración especial de 30 años de byhormiga. Una noche inolvidable para conmemorar tres décadas transformando la escena de eventos en Uruguay. Detalles próximamente.',
    image: '/mock-photos/event-4.jpeg',
  },
  {
    slug: 'minimal-mondays',
    name: 'MINIMAL MONDAYS',
    venue: 'Cine Universitario',
    date: '2026-06-14',
    day: '14',
    month: 'JUN',
    weekday: 'LUN',
    price: '$U 200 anticipadas',
    status: 'en-venta',
    description: 'Los lunes también se baila. Minimal techno y deep tech en una sesión exclusiva para verdaderos amantes del género.',
    image: '/mock-photos/event-5.jpg',
  },
  {
    slug: 'bass-culture',
    name: 'BASS CULTURE',
    venue: 'Club Malvín',
    date: '2026-06-21',
    day: '21',
    month: 'JUN',
    weekday: 'VIE',
    price: '$U 300 anticipadas',
    status: 'en-venta',
    description: 'Drum & bass, dubstep y bass music en su máxima expresión. Sistema de sonido de primer nivel.',
    image: '/mock-photos/event-1.jpeg',
  },
  {
    slug: 'cosmic-journey',
    name: 'COSMIC JOURNEY',
    venue: 'Sala del Museo',
    date: '2026-06-28',
    day: '28',
    month: 'JUN',
    weekday: 'VIE',
    price: '$U 380 anticipadas',
    status: 'proximamente',
    description: 'Experiencia audiovisual inmersiva. Música electrónica ambient y proyecciones 360° en un espacio único.',
    image: '/mock-photos/event-2.jpeg',
  },
]

// Mock data for gallery
export const mockGallery: GalleryItem[] = [
  {
    id: '1',
    slug: 'hormiga-negra-ix',
    event_name: 'HORMIGA NEGRA IX',
    date: 'MAR 2026',
    image: '/mock-photos/event-1.jpeg',
    photos: [
      {
        id: '1-1',
        image: '/mock-photos/event-1.jpeg',
        caption: 'Momento épico en HORMIGA NEGRA IX',
        order: 1,
      },
      {
        id: '1-2',
        image: '/mock-photos/event-2.jpeg',
        caption: 'La multitud vibrando al unísono',
        order: 2,
      },
      {
        id: '1-3',
        image: '/mock-photos/event-3.jpeg',
        caption: 'Luces y música en perfecta armonía',
        order: 3,
      },
      {
        id: '1-4',
        image: '/mock-photos/event-4.jpeg',
        caption: 'DJ set inolvidable',
        order: 4,
      },
    ],
  },
  {
    id: '2',
    slug: 'subterranea-vol-3',
    event_name: 'SUBTERRANEA VOL.3',
    date: 'FEB 2026',
    image: '/mock-photos/event-2.jpeg',
    photos: [
      {
        id: '2-1',
        image: '/mock-photos/event-2.jpeg',
        caption: 'Subterránea en su máxima expresión',
        order: 1,
      },
      {
        id: '2-2',
        image: '/mock-photos/event-3.jpeg',
        caption: 'Underground vibes',
        order: 2,
      },
      {
        id: '2-3',
        image: '/mock-photos/event-4.jpeg',
        caption: 'La Trastienda en modo electrónico',
        order: 3,
      },
    ],
  },
  {
    id: '3',
    slug: 'open-air-verano-2026',
    event_name: 'OPEN AIR VERANO',
    date: 'ENE 2026',
    image: '/mock-photos/event-3.jpeg',
    photos: [
      {
        id: '3-1',
        image: '/mock-photos/event-3.jpeg',
        caption: 'Festival al aire libre',
        order: 1,
      },
      {
        id: '3-2',
        image: '/mock-photos/event-4.jpeg',
        caption: 'Miles vibrando bajo el sol',
        order: 2,
      },
      {
        id: '3-3',
        image: '/mock-photos/event-5.jpg',
        caption: 'Parque Rodó en su mejor momento',
        order: 3,
      },
      {
        id: '3-4',
        image: '/mock-photos/event-1.jpeg',
        caption: 'Puesta de sol perfecta',
        order: 4,
      },
    ],
  },
  {
    id: '4',
    slug: 'nye-2026',
    event_name: 'NYE 2026',
    date: 'DIC 2025',
    image: '/mock-photos/event-4.jpeg',
    photos: [
      {
        id: '4-1',
        image: '/mock-photos/event-4.jpeg',
        caption: 'Fin de año épico',
        order: 1,
      },
      {
        id: '4-2',
        image: '/mock-photos/event-5.jpg',
        caption: 'La cuenta regresiva más esperada',
        order: 2,
      },
      {
        id: '4-3',
        image: '/mock-photos/event-1.jpeg',
        caption: 'Celebración inolvidable',
        order: 3,
      },
    ],
  },
  {
    id: '5',
    slug: 'hormiga-negra-viii',
    event_name: 'HORMIGA NEGRA VIII',
    date: 'NOV 2025',
    image: '/mock-photos/event-5.jpg',
    photos: [
      {
        id: '5-1',
        image: '/mock-photos/event-5.jpg',
        caption: 'Octava edición legendaria',
        order: 1,
      },
      {
        id: '5-2',
        image: '/mock-photos/event-1.jpeg',
        caption: 'Energía desbordante',
        order: 2,
      },
      {
        id: '5-3',
        image: '/mock-photos/event-2.jpeg',
        caption: 'Conexión total con la música',
        order: 3,
      },
    ],
  },
  {
    id: '6',
    slug: 'techno-marathon-2025',
    event_name: 'TECHNO MARATHON 2025',
    date: 'OCT 2025',
    image: '/mock-photos/event-3.jpeg',
    photos: [
      {
        id: '6-1',
        image: '/mock-photos/event-3.jpeg',
        caption: '12 horas de techno ininterrumpido',
        order: 1,
      },
      {
        id: '6-2',
        image: '/mock-photos/event-4.jpeg',
        caption: 'El público no paró de bailar',
        order: 2,
      },
      {
        id: '6-3',
        image: '/mock-photos/event-5.jpg',
        caption: 'Amanecer épico en la pista',
        order: 3,
      },
    ],
  },
  {
    id: '7',
    slug: 'warehouse-rave-sept',
    event_name: 'WAREHOUSE RAVE',
    date: 'SEP 2025',
    image: '/mock-photos/event-1.jpeg',
    photos: [
      {
        id: '7-1',
        image: '/mock-photos/event-1.jpeg',
        caption: 'Espacio industrial transformado',
        order: 1,
      },
      {
        id: '7-2',
        image: '/mock-photos/event-2.jpeg',
        caption: 'Sistema de sonido demoledor',
        order: 2,
      },
    ],
  },
  {
    id: '8',
    slug: 'beach-session-ago',
    event_name: 'BEACH SESSION',
    date: 'AGO 2025',
    image: '/mock-photos/event-2.jpeg',
    photos: [
      {
        id: '8-1',
        image: '/mock-photos/event-2.jpeg',
        caption: 'Sunset perfecto en Pocitos',
        order: 1,
      },
      {
        id: '8-2',
        image: '/mock-photos/event-3.jpeg',
        caption: 'Deep house junto al mar',
        order: 2,
      },
      {
        id: '8-3',
        image: '/mock-photos/event-4.jpeg',
        caption: 'La mejor vibra del verano',
        order: 3,
      },
    ],
  },
  {
    id: '9',
    slug: 'club-night-jul',
    event_name: 'CLUB NIGHT',
    date: 'JUL 2025',
    image: '/mock-photos/event-5.jpg',
    photos: [
      {
        id: '9-1',
        image: '/mock-photos/event-5.jpg',
        caption: 'Noche inolvidable en La Trastienda',
        order: 1,
      },
      {
        id: '9-2',
        image: '/mock-photos/event-1.jpeg',
        caption: 'La pista a reventar',
        order: 2,
      },
    ],
  },
  {
    id: '10',
    slug: 'underground-jun',
    event_name: 'UNDERGROUND',
    date: 'JUN 2025',
    image: '/mock-photos/event-4.jpeg',
    photos: [
      {
        id: '10-1',
        image: '/mock-photos/event-4.jpeg',
        caption: 'Experiencia única bajo tierra',
        order: 1,
      },
      {
        id: '10-2',
        image: '/mock-photos/event-5.jpg',
        caption: 'Los mejores DJs de la escena',
        order: 2,
      },
      {
        id: '10-3',
        image: '/mock-photos/event-1.jpeg',
        caption: 'Energía pura hasta el amanecer',
        order: 3,
      },
    ],
  },
]

// Mock data for sponsors - REMOVED - usar solo los sponsors reales del defaultSponsors en PartnersSection
export const mockSponsors: Sponsor[] = []

// Mock data for posts
export const mockPosts: Post[] = [
  {
    slug: 'byhormiga-trastienda-nueva-era',
    title: 'BYHORMIGA Y LA TRASTIENDA: UNA NUEVA ERA PARA LOS EVENTOS EN MONTEVIDEO',
    description:
      'El icónico venue montevideano y byhormiga unen fuerzas para crear experiencias inolvidables que redefinen la escena de eventos en Uruguay.',
    date: '18 MAR 2026',
    image: '/mock-photos/event-2.jpeg',
  },
  {
    slug: '30-anos-byhormiga-fernando-herrero',
    title: '30 AÑOS DE BYHORMIGA: CÓMO FERNANDO HERRERO TRANSFORMÓ LA ESCENA DE EVENTOS EN URUGUAY',
    description:
      'Un recorrido por tres décadas de innovación, creatividad y pasión por las experiencias que conectan a las personas.',
    date: '05 FEB 2026',
    image: '/mock-photos/event-4.jpeg',
  },
  {
    slug: 'mejores-momentos-hormiga-negra-ix',
    title: 'LOS MEJORES MOMENTOS DE HORMIGA NEGRA IX EN EL CINE UNIVERSITARIO',
    description:
      'Revivimos la novena edición de nuestro evento más emblemático a través de imágenes y testimonios de quienes lo vivieron.',
    date: '20 ENE 2026',
    image: '/mock-photos/event-1.jpeg',
  },
  {
    slug: 'escena-electronica-uruguay-2026',
    title: 'LA ESCENA ELECTRÓNICA EN URUGUAY ESTÁ VIVIENDO SU MEJOR MOMENTO',
    description:
      'Análisis del boom de la música electrónica en Uruguay y cómo ByHormiga ha sido parte fundamental de este crecimiento.',
    date: '12 MAR 2026',
    image: '/mock-photos/event-3.jpeg',
  },
  {
    slug: 'techno-culture-montevideo',
    title: 'MONTEVIDEO SE CONSOLIDA COMO CAPITAL DEL TECHNO EN SUDAMÉRICA',
    description:
      'DJs internacionales eligen Uruguay como destino preferido para sus tours latinoamericanos.',
    date: '28 FEB 2026',
    image: '/mock-photos/event-5.jpg',
  },
  {
    slug: 'sustentabilidad-eventos',
    title: 'BYHORMIGA LIDERA LA MOVIDA HACIA EVENTOS SUSTENTABLES',
    description:
      'Cómo la productora está implementando prácticas ecológicas sin sacrificar la calidad de la experiencia.',
    date: '15 FEB 2026',
    image: '/mock-photos/event-2.jpeg',
  },
]
