# Generated by Django 4.2.16 on 2026-07-29 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, upload_to='productions/logos/', verbose_name='Logo')),
                ('category', models.CharField(choices=[('matinee', 'Matineé'), ('plus15', '+15'), ('plus18', '+18'), ('coproduccion_internacional', 'Co-Producciones')], max_length=30, verbose_name='Categoría')),
                ('card_description', models.TextField(blank=True, help_text='Se usa como descripción para buscadores (SEO), no se muestra en el sitio.', verbose_name='Descripción corta')),
                ('hero_image', models.ImageField(blank=True, upload_to='productions/hero/', verbose_name='Foto de portada')),
                ('destacado', models.TextField(help_text='Frase grande que se anima palabra por palabra. Solo texto plano, sin HTML.', verbose_name='Texto destacado')),
                ('venues_intro', models.TextField(blank=True, verbose_name='Texto introductorio de venues')),
                ('closing_text', models.TextField(blank=True, verbose_name='Texto de cierre')),
                ('closing_image', models.ImageField(blank=True, upload_to='productions/closing/', verbose_name='Foto de cierre')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición dentro de su categoría (menor número = primero)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('side', models.CharField(choices=[('left', 'Foto a la izquierda'), ('right', 'Foto a la derecha'), ('full', 'Foto/video a pantalla completa')], default='right', max_length=10, verbose_name='Posición')),
                ('text', models.TextField(blank=True, verbose_name='Texto')),
                ('label', models.CharField(blank=True, help_text="Solo se usa con 'Foto a pantalla completa'", max_length=100, verbose_name='Etiqueta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición dentro de la producción (menor número = primero)', verbose_name='Orden')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='productions.production', verbose_name='Producción')),
            ],
            options={
                'verbose_name': 'Sección de producción',
                'verbose_name_plural': 'Secciones de producción',
                'ordering': ['production', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionVenue',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, upload_to='productions/venues/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = primero)', verbose_name='Orden')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='productions.production', verbose_name='Producción')),
            ],
            options={
                'verbose_name': 'Venue de producción',
                'verbose_name_plural': 'Venues de producción',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSectionImage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='productions/sections/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de rotación (menor número = primero)', verbose_name='Orden')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productions.productionsection', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Foto de sección',
                'verbose_name_plural': 'Fotos de sección',
                'ordering': ['order'],
            },
        ),
    ]
